-- AlterTable
ALTER TABLE "Car" ADD COLUMN "makes" VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN "type" VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE "Car" ALTER COLUMN "makes" DROP DEFAULT;
ALTER TABLE "Car" ALTER COLUMN "type" DROP DEFAULT;
